# Generated by Django 5.1.6 on 2025-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=50),
        ),
    ]
